#  Retail Sales Data Cleaning Project

## Objective
 -To clean and preprocess raw retail data for further analysis and dashboard creation.

## Steps Covered
- Data Loading
- Handling Missing Values
- Removing Duplicates
- Feature Engineering
- Data Export

In [12]:
# Importing required libraries for data analysis and visualization

import pandas as pd        # Used for data manipulation and analysis (DataFrames)
import numpy as np         # Used for numerical operations and array handling
import matplotlib.pyplot as plt   # Used for basic data visualization (charts/plots)
import seaborn as sns      # Used for advanced and attractive statistical visualizations

In [13]:
# Load dataset with proper encoding to handle special characters
df = pd.read_csv("Online Retail Data Set.csv", encoding='latin1')

In [14]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [18]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [19]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

## Removing Missing Values

- Rows with missing CustomerID and Description are removed to ensure clean and reliable data.
- Records without CustomerID represent anonymous transactions, which cannot be used for customer-level analysis like segmentation, retention, or RFM. So I removed them to maintain data quality

In [20]:
df = df.dropna(subset=['CustomerID'])

In [21]:
df = df.dropna(subset=['Description'])

In [15]:
df['CustomerID'] = df['CustomerID'].astype(int)

In [22]:
df = df.drop_duplicates()

In [23]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

## We are creating a new column 'Revenue' which is calculated as:
 Revenue = Quantity × UnitPrice. This helps in analyzing sales performance.

In [24]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [25]:
df['Description'] = df['Description'].str.strip()
df['Country'] = df['Country'].str.title()

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  object
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  object
 8   Revenue      401604 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 30.6+ MB

In [27]:
# Check null values
df['InvoiceDate'].isnull().sum()

# Fill missing dates (example)
#df['InvoiceDate'].fillna('2020-01-01', inplace=True)
df['InvoiceDate'] = df['InvoiceDate'].fillna('2020-01-01')

# OR drop rows with null dates
df = df[df['InvoiceDate'].notna()]

In [32]:
# Convert InvoiceDate column to proper datetime format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%d-%m-%Y %H:%M')

In [29]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
Revenue               float64
dtype: object

In [30]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [33]:
df.to_csv("cleaned_online_retail.csv", index=False)